services:
  aid-frontend:
    container_name: aid-frontend
    build:
      context: ./frontend
      args:
            - NODE_ENV=local
      dockerfile: frontend.Dockerfile
    ports:
      - 80:80

  aid-backend:
    container_name: aid-backend
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 3000:5000

#  aid_db:
