services:
  aid-frontend:
    container_name: aid-frontend
    build:
      context: ./frontend
      args:
            - NODE_ENV=local
      dockerfile: frontend.Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - aid-backend

  # this is a placeholder for when we have a domain
  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw

  aid-backend:
    container_name: aid-backend
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    volumes:
      - ./backend/aid_vault:/code/aid_vault
    # not needed anymore
    # ports:
    #   - 3000:3000
    depends_on:
      aid-db:
        condition: service_healthy

  aid-db:
    container_name: aid-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=name
      - POSTGRES_DB=aid-db
    volumes:
      - postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d aid-db -U name"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgresql:
