services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
            - NODE_ENV=local
      dockerfile: frontend.Dockerfile
    ports:
      - 80:80

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    volumes: 
      - ./backend/health_patterns:/code/health_patterns
    ports:
      - 3000:3000
    depends_on:
      db: 
        condition: service_healthy

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=name
      - POSTGRES_DB=db
    volumes:
      - postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db -U name"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgresql:
