services:
  aid-frontend:
    container_name: aid-frontend
    build:
      context: ./frontend
      args:
            - NODE_ENV=local
      dockerfile: frontend.Dockerfile
    ports:
      - 80:80

  aid-backend:
    container_name: aid-backend
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    volumes: 
      - ./backend/aid_vault:/code/aid_vault
    ports:
      - 5000:5000
    depends_on:
      aid-db: 
        condition: service_healthy

  aid-db:
    container_name: aid-db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=name
      - POSTGRES_DB=aid-db
    volumes:
      - postgresql:/db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d aid-db -U name"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgresql: {}

